#!/bin/bash

./reconstruct_belle2_mc_run_range.sh 001
./reconstruct_belle2_mc_run_range.sh 001
./reconstruct_belle2_mc_run_range.sh 002
./reconstruct_belle2_mc_run_range.sh 003
./reconstruct_belle2_mc_run_range.sh 004
./reconstruct_belle2_mc_run_range.sh 005
./reconstruct_belle2_mc_run_range.sh 006
./reconstruct_belle2_mc_run_range.sh 007
./reconstruct_belle2_mc_run_range.sh 008
./reconstruct_belle2_mc_run_range.sh 009
./reconstruct_belle2_mc_run_range.sh 010
./reconstruct_belle2_mc_run_range.sh 011
./reconstruct_belle2_mc_run_range.sh 012
./reconstruct_belle2_mc_run_range.sh 013
./reconstruct_belle2_mc_run_range.sh 014
./reconstruct_belle2_mc_run_range.sh 015
./reconstruct_belle2_mc_run_range.sh 016
./reconstruct_belle2_mc_run_range.sh 017
./reconstruct_belle2_mc_run_range.sh 018
./reconstruct_belle2_mc_run_range.sh 019
./reconstruct_belle2_mc_run_range.sh 020
./reconstruct_belle2_mc_run_range.sh 021
./reconstruct_belle2_mc_run_range.sh 022
./reconstruct_belle2_mc_run_range.sh 023
./reconstruct_belle2_mc_run_range.sh 024
./reconstruct_belle2_mc_run_range.sh 025
./reconstruct_belle2_mc_run_range.sh 026
./reconstruct_belle2_mc_run_range.sh 027
./reconstruct_belle2_mc_run_range.sh 028
./reconstruct_belle2_mc_run_range.sh 029
./reconstruct_belle2_mc_run_range.sh 030
./reconstruct_belle2_mc_run_range.sh 031
./reconstruct_belle2_mc_run_range.sh 032
./reconstruct_belle2_mc_run_range.sh 033
./reconstruct_belle2_mc_run_range.sh 034
./reconstruct_belle2_mc_run_range.sh 035
./reconstruct_belle2_mc_run_range.sh 036
./reconstruct_belle2_mc_run_range.sh 037
./reconstruct_belle2_mc_run_range.sh 038
./reconstruct_belle2_mc_run_range.sh 039
./reconstruct_belle2_mc_run_range.sh 040
./reconstruct_belle2_mc_run_range.sh 041
./reconstruct_belle2_mc_run_range.sh 042
./reconstruct_belle2_mc_run_range.sh 043
./reconstruct_belle2_mc_run_range.sh 044
./reconstruct_belle2_mc_run_range.sh 045
./reconstruct_belle2_mc_run_range.sh 046
./reconstruct_belle2_mc_run_range.sh 047
./reconstruct_belle2_mc_run_range.sh 048
./reconstruct_belle2_mc_run_range.sh 049
./reconstruct_belle2_mc_run_range.sh 050
./reconstruct_belle2_mc_run_range.sh 051
./reconstruct_belle2_mc_run_range.sh 052
./reconstruct_belle2_mc_run_range.sh 053
./reconstruct_belle2_mc_run_range.sh 054
./reconstruct_belle2_mc_run_range.sh 055
./reconstruct_belle2_mc_run_range.sh 056
./reconstruct_belle2_mc_run_range.sh 057
./reconstruct_belle2_mc_run_range.sh 058
./reconstruct_belle2_mc_run_range.sh 059
./reconstruct_belle2_mc_run_range.sh 060
./reconstruct_belle2_mc_run_range.sh 061
./reconstruct_belle2_mc_run_range.sh 062
./reconstruct_belle2_mc_run_range.sh 063
./reconstruct_belle2_mc_run_range.sh 064
./reconstruct_belle2_mc_run_range.sh 065
./reconstruct_belle2_mc_run_range.sh 066
./reconstruct_belle2_mc_run_range.sh 067
./reconstruct_belle2_mc_run_range.sh 068
./reconstruct_belle2_mc_run_range.sh 069
./reconstruct_belle2_mc_run_range.sh 070
./reconstruct_belle2_mc_run_range.sh 071
./reconstruct_belle2_mc_run_range.sh 072
./reconstruct_belle2_mc_run_range.sh 073
./reconstruct_belle2_mc_run_range.sh 074
./reconstruct_belle2_mc_run_range.sh 075
./reconstruct_belle2_mc_run_range.sh 076
./reconstruct_belle2_mc_run_range.sh 077
./reconstruct_belle2_mc_run_range.sh 078
./reconstruct_belle2_mc_run_range.sh 079
./reconstruct_belle2_mc_run_range.sh 080
./reconstruct_belle2_mc_run_range.sh 081
./reconstruct_belle2_mc_run_range.sh 082
./reconstruct_belle2_mc_run_range.sh 083
./reconstruct_belle2_mc_run_range.sh 084
./reconstruct_belle2_mc_run_range.sh 085
./reconstruct_belle2_mc_run_range.sh 086
./reconstruct_belle2_mc_run_range.sh 087
./reconstruct_belle2_mc_run_range.sh 088
./reconstruct_belle2_mc_run_range.sh 089
./reconstruct_belle2_mc_run_range.sh 090
./reconstruct_belle2_mc_run_range.sh 091
./reconstruct_belle2_mc_run_range.sh 092
./reconstruct_belle2_mc_run_range.sh 093
./reconstruct_belle2_mc_run_range.sh 094
./reconstruct_belle2_mc_run_range.sh 095
./reconstruct_belle2_mc_run_range.sh 096
./reconstruct_belle2_mc_run_range.sh 097
./reconstruct_belle2_mc_run_range.sh 098
./reconstruct_belle2_mc_run_range.sh 099
./reconstruct_belle2_mc_run_range.sh 100

