Import('env')

env['SUBLIB'] = True
env['LIBS'] = ['framework', 'analysis', 'analysis_dataobjects', 
	      'analysis_VertexFitting', 'analysis_DecayDescriptor',
	      'analysis_utility', '$ROOT_LIBS', 'CLHEP']

Return('env')
